spring:
  data:
    mongodb:
      host: localhost # mongo no docker-compose | localhost local
      port: 27017
      database: reservas
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

reservations:
  feign:
    usersApi: https://628a3c025da6ddfd5d612a6c.mockapi.io
    resourcesApi: https://628a3c025da6ddfd5d612a6c.mockapi.io
    lessonsApi: https://628a3c025da6ddfd5d612a6c.mockapi.io

server:
  port: 8081